
project_id = "tarjnmziaghkzosivsqk"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[functions]
[functions.process-video-queue]
verify_jwt = true
[functions.google-drive-oauth]
verify_jwt = true
[functions.google-drive-oauth-callback]
verify_jwt = false
[functions.google-drive-files]
verify_jwt = true
[functions.google-drive-upload]
verify_jwt = true
[functions.check-new-videos]
verify_jwt = true
[functions.create-checkout]
verify_jwt = true
[functions.check-subscription]
verify_jwt = true
[functions.fetch-platform-videos]
verify_jwt = true
[functions.process-video]
verify_jwt = true
[functions.stripe-webhook]
verify_jwt = false
[functions.tiktok-oauth]
verify_jwt = true
[functions.tiktok-oauth-callback]
verify_jwt = false
[functions.youtube-oauth]
verify_jwt = true
[functions.youtube-oauth-callback]
verify_jwt = false
