
project_id = "tarjnmziaghkzosivsqk"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "https://opaldesign.fr"
additional_redirect_urls = ["https://opaldesign.fr/*", "http://localhost:3000/*"]

[functions]
[functions.check-new-videos]
verify_jwt = true
[functions.fetch-platform-videos]
verify_jwt = true
[functions.process-video-queue]
verify_jwt = true
[functions.process-video]
verify_jwt = true
[functions.tiktok-oauth]
verify_jwt = true
[functions.tiktok-oauth-callback]
verify_jwt = false
[functions.youtube-oauth]
verify_jwt = true
[functions.youtube-oauth-callback]
verify_jwt = false
