// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tarjnmziaghkzosivsqk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhcmpubXppYWdoa3pvc2l2c3FrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNTI1MDksImV4cCI6MjA2MDcyODUwOX0.ghjqIPXJjaiVOJ-PfDpY56CQOomKijD5WL6gZEHoNZ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);